version: "3.8"

services:
  postgres:
    container_name: habraparser_postgres
    image: postgres:12.3-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - env

  rabbitmq:
    container_name: habraparser_rabbitmq
    image: rabbitmq

  celery:
    container_name: habraparser_celery
    build:
      context: ./
    command: celery -A habraparser worker -l info
    volumes:
      - ./:/opt/app
    depends_on:
      - postgres
      - rabbitmq

  celery-beat:
    container_name: habraparser_celery_beat
    build: ./
    command: celery -A habraparser beat -l info
    volumes:
      - ./:/opt/app
    depends_on:
      - celery

  django:
    container_name: habraparser_django
    build: ./
    command: bash -c "python /opt/app/manage.py makemigrations --noinput && python /opt/app/manage.py migrate --noinput && python /opt/app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - celery

volumes:
  pg_data: